### ISSUE TITLE
What do we do with this?

### ISSUE THREAD

**Issue by amazinigmech2418** [heb12/backend#1]
I know some backend languages, but what is this exactly for? Do we make a downloadable copy of heb12 to run with backend languages? If so, I don't think PHP would be the best since PHP is only good for api requests. I would say node.js for backend. It could create a local server for running the backend scripts.

**Comment by MasterOfTheTiger** [comment]
This is for @edxtech's backend code he put in the main repo. I though was going to move it, but I guess I will do it.
